eos_core:                                   # Section for S3 background delete config
   endpoint: "http://127.0.0.1:7081"                       # Service specified for EOS mero client
   service: "eoscore"                                           # Default region specified for EOS mero client
   default_region: "us-west2"                              # EOS mero client will use the specified host
   access_key: "AKIAJPINPFRBTPAYXAHZ"                      # Access Key corresponding to account-name "s3-background-delete-svc"
   secret_key: "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"  # Secret Key corresponding to account-name "s3-background-delete-svc"
   daemon_mode: "True"                                     # S3background process run in daemon mode and ST's run in non-daemon mode.


logconfig:                                  # Section for scheduler & processor loggers.

   # Logging facility for Python https://docs.python.org/3/library/logging.html

   scheduler_logger_name: "object_recovery_scheduler"                                         # Root logger name for scheduler
   processor_logger_name: "object_recovery_processor"                                         # Root logger name for processor
   logger_directory: "/var/log/seagate/s3/s3backgrounddelete"                                 # Log directory location for background delete
   scheduler_log_file: "/var/log/seagate/s3/s3backgrounddelete/object_recovery_scheduler.log" # Log file path for background delete scheduler
   processor_log_file: "/var/log/seagate/s3/s3backgrounddelete/object_recovery_processor.log" # Log file path for background delete processor
   file_log_level: 10                                                                         # Sets the threshold for above file loggers to level specified. https://docs.python.org/3/library/logging.html#levels
   console_log_level: 40                                                                      # Sets the threshold for console loggers to level specified. https://docs.python.org/3/library/logging.html#levels
   log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"                         # Sets the specifed log format https://docs.python.org/3/library/logging.html#logging.Formatter
   max_bytes: 5242880                                                                         # Max size of a log files is set to 5mb
   backup_count: 5                                                                            # Max number of log files that can exist
rabbitmq:                                    # Section for RabbitMQ configs

   # RabbitMQ overview:  https://www.rabbitmq.com/getstarted.html

    username: "eos-s3"                                      # Username used to communicate with RabbitMQ
    password: "password"                                    # Password corresponding to username
    host: "127.0.0.1"                                       # Host on which RabbitMQ is runnning
    queue: "s3_delete_obj_job_queue"                        # Queue name used in RabbitMQ
    exchange: ""                                            # Exchanges control the routing of messages to queues.
    exchange_type: "direct"                                 # Exchanges type includes direct, fanout, topic exchange, header exchange
    mode: 2                                                 # Valid values are Non-persistent (1) or persistent (2). persistent ensures that the task_queue queue won't be lost even if RabbitMQ restarts.
    durable: "True"                                         # Ensure that RabbitMQ will never lose our queue.
    schedule_interval_secs: 900                             # Schedule Interval is time period at which object recovery scheduler will be executed (in seconds)

indexid:

   probable_delete_index_id: "AAAAAAAAAHg=-AwAQAAAAAAA="      # Index id containing list of probable delete object oid. This is fixed index id shared with s3server.
   global_instance_index_id: "AAAAAAAAAHg=-BAAQAAAAAAA="      # Index id containing global instance id's. This is also fixed index id shared with s3server.
   max_keys: 1000                                             # Maximum number of keys in global index to be queried from list of probable delete object oid.

leakconfig:                                  # Section for object leak config
   leak_processing_delay_in_mins: 15                          # Time delay in mins after which probable delete entry is procesed for leak.
   version_processing_delay_in_mins: 5                        # Time delay in mins after which object version is processed