# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: trailing-whitespace
      # - id: end-of-file-fixer
      # - id: check-merge-conflict
      # - id: check-case-conflict
      # - id: check-json
      # - id: check-toml
      # - id: check-yaml
      # - id: pretty-format-json
      #   args: [--autofix, --no-ensure-ascii, --no-sort-keys]
      # - id: check-ast
      # - id: debug-statements
      # - id: check-docstring-first
  # - repo: local
    # hooks:
      # - id: black
      #   args:
      #     - --safe
      #     - --quiet
      #   name: local black
      #   entry: poetry run black
      #   language: system
      #   types: [python]
      # - id: flake8
      #   name: local flake8
      #   description: wemake-python-styleguide enforcement
      #   entry: poetry run flake8
      #   files: ^({PROJECT_NAME}/|tests/)
      #   args: ["--config=setup.cfg"]
      #   language: system
      #   types: [python]
      # - id: mypy
      #   args:
      #     - --show-error-codes
      #   name: local mypy
      #   description: runs mypy
      #   entry: poetry run mypy
      #   language: system
      #   types: [python]
      # - id: coverage
      #   name: local pytest coverage
      #   description: runs pytest along with coverage
      #   entry: poetry run pytest --cov {PROJECT_NAME} tests
      #   files: ^({PROJECT_NAME}/|tests/)
      #   language: system
      #   types: [python]
      # - id: safety
      #   name: local safety
      #   description: check for vulnerabilities in packages.
      #   entry: poetry run safety check
      #   language: system
      #   types: [python]
      #   pass_filenames: false
      # - id: pylint
      #   name: pylint
      #   entry: poetry run pylint
      #   language: system
      #   exclude: tests/
      #   types:
      #     - python
  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.4
  #   hooks:
  #     - id: bandit
  #       args:
  #         - --ini
  #         - setup.cfg
  #       exclude: tests/
  # - repo: https://github.com/asottile/blacken-docs
  #   rev: v1.12.1
  #   hooks:
  #     - id: blacken-docs
  #       additional_dependencies:
  #         - black==22.1.0
  # - repo: https://github.com/PyCQA/flake8
  #   rev: 4.0.1
  #   hooks:
  #     - id: flake8
  #       additional_dependencies:
  #         - flake8-blind-except
  #         - flake8-bugbear
  #         - flake8-comprehensions
  #         - flake8-debugger
  #         - flake8-docstrings
  #         - flake8-isort
  #         - flake8-polyfill
  #         - flake8-pytest
  #         - flake8-quotes
  #         - flake8-typing-imports
  #         - yesqa
  # - repo: https://github.com/pre-commit/pygrep-hooks
  #   rev: v1.9.0
  #   hooks:
  #     - id: python-check-blanket-noqa
  #     - id: python-check-mock-methods
  #     - id: python-no-eval
  #     - id: python-no-log-warn
  #     - id: rst-backticks
  # - repo: https://github.com/asottile/pyupgrade
  #   rev: v2.34.0
  #   hooks:
  #     - id: pyupgrade
  #       args:
  #         - --py37-plus
  # - repo: https://github.com/PyCQA/isort
  #   rev: 5.10.1
  #   hooks:
  #     - id: isort
  # - repo: https://github.com/myint/autoflake
  #   rev: v1.4
  #   hooks:
  #     - id: autoflake
  #       args:
  #         - --in-place
  #         - --remove-all-unused-imports
  #         - --remove-unused-variables
  #         - --remove-duplicate-keys
  #         - --ignore-init-module-imports
  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v2.7.1
  #   hooks:
  #     - id: prettier
  #       stages:
  #         - commit
  # - repo: https://github.com/commitizen-tools/commitizen
  #   rev: v2.27.1
  #   hooks:
  #     - id: commitizen
  #       stages:
  #         - commit-msg
  # - repo: https://github.com/openstack/bashate
  #   rev: 2.1.0
  #   hooks:
  #     - id: bashate
  #       args:
  #         - -i
  #         - E006
  # - repo: https://github.com/shellcheck-py/shellcheck-py
  #   rev: v0.8.0.4
  #   hooks:
  #     - id: shellcheck
