---
- name: Setup yum repos for development (devvm and release test vm)
  hosts: s3*
  remote_user: root
  gather_facts: yes

  tasks:
    - name: Add repository for lustre in release 7.5.1804
      when: (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat') and (facter_operatingsystemrelease == '7.5.1804')
      yum_repository:
        name: releases_eos_lustre
        description: Yum repo for lustre
        baseurl: http://ci-storage.mero.colo.seagate.com/releases/master/last_successful/lustre/repo/
        gpgcheck: no
        priority: 1

    - name: Add repository for lustre s3server mero and halon in release 7.7.1908
      when: (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat') and (facter_operatingsystemrelease == '7.7.1908')
      yum_repository:
        name: releases_eos_lustre_s3server_halon_mero
        description: Yum repo for lustre s3server halon mero
        baseurl: http://ci-storage.mero.colo.seagate.com/releases/eos/integration/centos-7.7.1908/last_successful/
        gpgcheck: no
        priority: 1


    - name: Add repository for halon in release 7.5.1804
      when: (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat') and (facter_operatingsystemrelease == '7.5.1804')
      yum_repository:
        name: releases_eos_halon
        description: Yum repo for halon
        baseurl: http://ci-storage.mero.colo.seagate.com/releases/master/last_successful/halon/repo/
        gpgcheck: no
        priority: 1

    - name: Add repository for mero in release 7.5.1804
      when: (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat') and (facter_operatingsystemrelease == '7.5.1804')
      yum_repository:
        name: releases_eos_mero
        description: Yum repo for mero
        baseurl: http://ci-storage.mero.colo.seagate.com/releases/master/last_successful/mero/repo/
        gpgcheck: no
        priority: 1

    - name: Add repository for s3server in release 7.5.1804
      when: (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat') and (facter_operatingsystemrelease == '7.5.1804')
      yum_repository:
        name: releases_eos_s3server
        description: Yum repo for s3server
        baseurl: http://ci-storage.mero.colo.seagate.com/releases/master/last_successful/s3server/repo/
        gpgcheck: no
        priority: 1

    - name: Add S3 deps repository for major version 7
      when: (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat') and (ansible_distribution_major_version == '7')
      yum_repository:
        name: releases_s3server_uploads
        description: Yum repo for S3 server dependencies
        baseurl: http://ci-storage.mero.colo.seagate.com/releases/eos/s3server_uploads/
        gpgcheck: no
        priority: 1

    - name: Add S3 deps repository for major version 8
      when: (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat') and (ansible_distribution_major_version == '8')
      yum_repository:
        name: releases_s3server_uploads
        description: Yum repo for S3 server dependencies for version 8
        baseurl: http://ci-storage.mero.colo.seagate.com/releases/eos/s3server_uploads/centos8/
        gpgcheck: no
        priority: 1

    - name: Add Provisioner epel 7 mirror
      when: (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat') and (ansible_distribution_major_version == '7')
      yum_repository:
        name: prvsnr_local_repository
        description: Yum local repo for S3 server dependencies
        baseurl: http://ci-storage.mero.colo.seagate.com/prvsnr/vendor/centos/epel/
        gpgcheck: no
        priority: 1

    - name: Add Provisioner epel 8 mirror
      when: (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat') and (ansible_distribution_major_version == '8')
      yum_repository:
        name: prvsnr_local_repository
        description: Yum local repo for S3 server dependencies
        # TODO Change it from public to mirror repo, once available
        baseurl: http://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/
        gpgcheck: no
        priority: 1
