---

# Prerequisites: Necessary yum repos setup, possibly jenkins_yum_repos.yml

- name: Install yum-utils if not present
  yum:
    name: yum-utils
    state: installed

- name: Install S3 server development build dependencies & tools
  # TODO Currently mero is not supported for CentOS 8, when support is there remove below check
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat') and (ansible_distribution_major_version == '7')
  command: yum-builddep -v -y {{ s3_src }}/rpms/s3/s3rpm.spec

- name: Install S3 server development build dependencies & tools
  # TODO Currently mero is not supported for CentOS 8, when support is there, above yum-builddep (without disabling mero)
  # will suffice for both CentOS 7 and 8, remove this one
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat') and (ansible_distribution_major_version == '8')
  command: yum-builddep -v -y {{ s3_src }}/rpms/s3/s3rpm.spec --define "disable_eoscore_dependencies 1"

- name: Install s3iamcli development build dependencies & tools
  command: yum-builddep -y {{ s3_src }}/rpms/s3iamcli/s3iamcli.spec

- name: Install dependency for s3cmd version 1.6.1-1.el7
  # In case of RHEL 8 higher version of s3cmd being used
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat') and (ansible_distribution_major_version == '7')
  yum: pkg={{item}} state=installed
  with_items:
    - python-dateutil

- name: Install python modules to build python36 dependencies
  yum: pkg={{item}} state=installed
  with_items:
    - "{{python_version}}-pytest"
    - "{{python_version}}-pika"
    - "{{python_version}}-jsonschema"
    - "{{python_version}}-nose"
    - "{{python_version}}-mock"
    - "{{python_version}}-ply"
