---

- name: Bareos node setup for S3 testing
  hosts: bareos
  remote_user: root
  gather_facts: yes

  vars_prompt:
    - name: "s3_host_ip"
      prompt: "Enter the host on which S3 is configured:"
      private: no

    - name: "s3_bucket_name"
      prompt: "Enter the S3 bucket name:"
      private: no

    - name: "s3_host_endpoint"
      prompt: "Enter the S3 service endpoint domain:"
      private: no
      default: "s3.seagate.com"

    - name: "s3_access_key"
      prompt: "Enter S3 access key:"
      private: no

    - name: "s3_secret_key"
      prompt: "Enter S3 access key:"
      private: yes

  vars:
      s3_host_endpoint: "seagatebucket.s3.seagate.com"
      iam_url_endpoints: "iam.seagate.com sts.seagate.com s3.seagate.com"

  tasks:
    - name: Install epel repo
      yum: pkg={{item}} state=installed
      with_items:
        - epel-release

    - name: Download bareos repo file
      get_url:
        url: http://download.bareos.org/bareos/release/latest/CentOS_7/bareos.repo
        dest: /etc/yum.repos.d/bareos.repo
        mode: 0644

    - name: Install bareos packages
      yum: pkg={{item}} state=installed
      with_items:
        - bareos
        - bareos-database-sqlite3

    - name: Install bareos backend for S3
      yum: pkg={{item}} state=installed
      with_items:
        - libdroplet-devel
        - bareos-storage-droplet

    - name: Setup the DB
      shell: sqlite3 /var/lib/bareos/bareos.db < /usr/lib/bareos/scripts/ddl/creates/sqlite3.sql
      args:
        creates: /var/lib/bareos/bareos.db

    - name: Setup permissions for db file to be owned by bareos user
      command: chown bareos:bareos /var/lib/bareos/bareos.db

    - name: Setup permissions for db file for r/w
      command: chmod 0660 /var/lib/bareos/bareos.db

    - name: Configure S3 storage
      template:
        src: templates/bareos/s3_storage.conf
        dest: /etc/bareos/bareos-dir.d/storage/s3_storage.conf
        owner: bareos
        group: bareos

    - name: Configure S3 Device
      template:
        src: templates/bareos/s3_device.conf
        dest: /etc/bareos/bareos-sd.d/device/s3_device.conf
        owner: bareos
        group: bareos

    - name: Ensures /etc/bareos/bareos-sd.d/device/droplet dir exists
      file:
        path: /etc/bareos/bareos-sd.d/device/droplet
        state: directory
        owner: bareos
        group: bareos

    - name: Configure S3 droplet
      template:
        src: templates/bareos/droplet.profile
        dest: /etc/bareos/bareos-sd.d/device/droplet/droplet.profile
        owner: bareos
        group: bareos

    - name: Configure S3 FileSet
      template:
        src: templates/bareos/s3files.conf
        dest: /etc/bareos/bareos-dir.d/fileset/s3files.conf
        owner: bareos
        group: bareos

    - name: Configure S3 job definition resource file
      template:
        src: templates/bareos/S3Job.conf
        dest: /etc/bareos/bareos-dir.d/jobdefs/S3Job.conf
        owner: bareos
        group: bareos

    - name: Configure S3 backup job
      template:
        src: templates/bareos/BackupToS3.conf
        dest: /etc/bareos/bareos-dir.d/job//BackupToS3.conf
        owner: bareos
        group: bareos

    - name: Configure S3 restore job
      template:
        src: templates/bareos/RestoreFiles.conf
        dest: /etc/bareos/bareos-dir.d/job/RestoreFiles.conf
        owner: bareos
        group: bareos

    - name: restart bareos-dir
      service:
        name: bareos-dir
        state: restarted

    - name: restart bareos-sd
      service:
        name: bareos-sd
        state: restarted

    - name: restart bareos-fd
      service:
        name: bareos-fd
        state: restarted

    - name: Add IP address of S3 server node to hosts.
      blockinfile:
        path: /etc/hosts
        block: |
          {{ item.ip }} {{ item.name }}
        marker: "# {mark} ANSIBLE MANAGED BAREOS BLOCK {{ item.name }}"
      with_items:
        - { name: "{{s3_host_endpoint}}", ip: "{{s3_host_ip}}" }
        - { name: "{{iam_url_endpoints}}", ip: "{{s3_host_ip}}" }


    - name: Open bareos director port so bconsole can connect remotely
      command: firewall-cmd --zone=public --add-port=9101/tcp --permanent

    - name: Restart firewall
      command: firewall-cmd --reload
