---
  # Mostly we wont need this as the DEV VM base image has these installed.
- name: Setup mero dev vm dependencies
  hosts: merodevvm
  remote_user: root
  gather_facts: yes
  vars:
    lustre_client_rpm: lustre-client-2.11.0-1.el7.centos.x86_64.rpm
    lustre_client_devel_rpm: lustre-client-devel-2.11.0-1.el7.centos.x86_64.rpm
    kmod_lustre_client_rpm: kmod-lustre-client-2.11.0-1.el7.centos.x86_64.rpm

  tasks:
    - name: Copy lustre rpms to configured node
      copy:
        src: files/lustre
        dest: /tmp/s3devvmsetup

    - name: Install lustre rpms
      yum: pkg={{item}} state=present
      with_items:
        - /tmp/s3devvmsetup/lustre/{{ lustre_client_rpm }}
        - /tmp/s3devvmsetup/lustre/{{ lustre_client_devel_rpm }}
        - /tmp/s3devvmsetup/lustre/{{ kmod_lustre_client_rpm }}

    - name: Configure lnet
      template:
        src: templates/lnet.conf
        dest: /etc/modprobe.d/lnet.conf

    - name: Add the lnet module
      modprobe:
        name: lnet
        state: present

    - name: Enable modprobe lnet on reboot
      lineinfile:
        path: /etc/modules-load.d/lnet.conf
        line: 'lnet'
        create: yes

    - name: Configure lnet
      command: lctl net up

    - name: Enable lnet up on reboot
      lineinfile:
        path: /etc/profile
        line: 'lctl net up'

    - name: Test lnet
      command: lctl list_nids

    - name: Install mero development utils
      yum: pkg={{item}} state=installed
      with_items:
        - asciidoc
        - attr
        - autoconf
        - automake
        - binutils-devel
        - expect
        - facter
        - gcc
        - gcc-c++
        - gccxml
        - cmake
        - genders
        - glibc-headers
        - libaio-devel
        - libtool
        - libuuid-devel
        - libyaml
        - libyaml-devel
        - perl-autodie
        - perl-File-Find-Rule
        - perl-File-Slurp
        - perl-IO-All
        - perl-List-MoreUtils
        - perl-XML-LibXML
        - perl-YAML-LibYAML
        - psmisc
        - python-devel
        - python-ply
        - PyYAML
        - rpm-build
        - ruby
        - rubygem-net-ssh
        - systemd-devel
        - time
